### ISSUE TITLE
How to compute the delta_EV_tables for my camera?

### ISSUE THREAD

**Issue by rossihwang** [MIT-Bilab/vo-autoexpose#1]
Hi, I've already got the PRF of my camera. How can I compute the delta_EV_tables? Thank you

**Comment by marcandrebegin** [comment]
Hi, 
If you have the PRF of the camera, then it means you can express the intensity of a pixel as a function of the exposure value*. It is defined as

EV = -log2(exposure_time_seconds*exposure_gain) = -log2(exposure_time_seconds) -(log2(10)/20)*exposure_gain_dB

Now consider a vector of pixel intensities I_in = [0,1,2,...,255]. Each delta_EV_table corresponds to a different change in EV. Say for instance you want to compute the delta_EV_table associated with delta_EV = -2.0. Then you can 
1. Use the inverse of the camera PRF to determine the EV associated to each element in I_in. Let's call that vector EV_in.
2. Subtract 2.0 from each element in EV_in. Call that new vector EV_out.
3. Use the camera PRF to determine the pixel intensity associated to each element of EV_out. Call that new vector I_out.

Then I_out is the delta_EV_table associated with delta_EV = -2.0.

*Note that the exposure value is the **negative** of the exposure level defined in the paper. I know this is confusing, but I have not had the time to update the code to use the exposure level as defined in the paper.

**Comment by rossihwang** [comment]
Thank you. In addition, the domain of the PRF and inverse PRF should be truncated properly to avoid being extrapolated by the fitting function.
